### ISSUE TITLE
Jenkins 2.x support ? 

### ISSUE THREAD

**Issue by mnsanghvi** [jenkinsci/pipeline-view-plugin#7]
Does this plug-in work with the built-in Pipelines API that is part of Jenkins 2.x ? 

I am not seeing any of the pipelines that I have setup when using this plug-in.  

Or am I missing anything ?  Since there is nothing mentioned in the README about how to 
set it up or any related information.

**Comment by bsideup** [comment]
@mnsanghvi actually, this plugin IS created for J 2.x :D 

It should render the pipeline when you open the build, not the job. If it doesn't - let me know, there might be something broken because pipelines are under active development

**Comment by mnsanghvi** [comment]
It does not render anything.  All I get is a blank page.  I have attached a screenshot.
<img width="1229" alt="screenshot 2016-09-20 at 15 19 54" src="https://cloud.githubusercontent.com/assets/1726664/18686096/ae58cd6c-7f48-11e6-94bd-0526107bec22.png">  

In the default Pipeline dashboard this is what it looks like:

<img width="1230" alt="screenshot 2016-09-20 at 15 42 49" src="https://cloud.githubusercontent.com/assets/1726664/18686165/f533db64-7f48-11e6-8c7e-68d12e5d5eeb.png">

**Comment by bsideup** [comment]
Ok, thanks, I'll take a look tomorrow. Sorry for that!

**Comment by mnsanghvi** [comment]
Thanks.  Let me know if you need anything from me.

**Comment by mnsanghvi** [comment]
Hi, just wondering if you had any updates on this ?  

In case it helps, I've got the following:

 jenkins                          version 2.7.4 LTS
 pipeline-view-plugin   version 0.3.1

All pipeline plug-ins are updated to the latest version and Jenkins has been re-started after the update.

**Comment by bsideup** [comment]
@mnsanghvi should be fixed with 0.4.0.
